name: 'Check pull request'

on:
  pull_request:
    branches: [main]
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'Roadmap/**'
      - '!Roadmap/**/*.md'

jobs:
  check-title:
    name: Check title
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository to virtual machine
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Check title of the pull request
        uses: ./.github/actions/pull-requests/check-title
        with:
          title: ${{ github.event.pull_request.title }}

  get-committed-files:
    needs: [check-title]
    name: Get committed files
    runs-on: ubuntu-latest
    outputs:
      committed-files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    steps:
      - name: Clone repository to virtual machine
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get committed files of the pull request
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          separator: '\n'

  check-committed-files:
    needs: [get-committed-files]
    name: Check committed files
    runs-on: ubuntu-latest
    outputs:
      committed-file: ${{ steps.changed-files.outputs.committed-file }}
    steps:
      - name: Clone repository to virtual machine
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Check committed files of the pull request
        id: changed-files
        uses: ./.github/actions/pull-requests/check-committed-files
        with:
          committed-files: ${{ needs.get-committed-files.outputs.committed-files }}

  check-committed-file:
    needs: [check-committed-files]
    name: Check committed file
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository to virtual machine
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Check committed file of the pull request
        uses: ./.github/actions/pull-requests/check-committed-file
        with:
          author: ${{ github.event.pull_request.user.name || github.actor }}
          committed-file: ${{ needs.check-committed-files.outputs.committed-file }}
          title: ${{ github.event.pull_request.title }}

permissions:
  pull-requests: read
