name: Stats

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # To allow the action to write back to the repo.
    permissions:
      contents: write
    
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      
      - name: Seting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Run script
        run: python ./Roadmap/stats.py

      # A GitHub Action to detect changed files during a Workflow run and to commit and push them back to the GitHub repository.
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated stats.py
          commit_author: fbolanos31 [Github Actions]
